---
layout: cv
title: Simon Sung CV
---
# Simon Sung
Computer Science | Mobile Development | Software Development

<div id="https://github.com/chengensung1219/ds_portfolio">
<a href="chengensung1219@gmail.com">chengensung1219@gmail.com</a>
| <a href="https://www.linkedin.com/in/chengensung1219">My LinkedIn page</a>
</div>


## Currently

I am a BYU-Idaho student, major in computer science, and currently looking for a full time job oportunity for software engineering, mobile development, or the position relate to my major.


### Key Skills

- __Proficient Skills:__ Swift, SwiftUI, C#, and Python
- __Developing Skills:__ Java, C++, Google Script, HTML, CSS, and JavaScript
- __Other Skills:__ Mandarin, Jira, Trello, Word, Excel, and PowerPoint
- __Soft Skills:__ Problem Solving, Team Work, Adaptive Learning, Time Management, and Communication


## Education

`January 2023 - December 2023`
__Brigham Young University - Hawaii__

- Bachelor Degree in Computer Science 

`January 2024 - now`
__Brigham Young University - Idaho__

- Bachelor Degree in Computer Science 



## Professional Experience


#### Faculty Technology Center: Technology Specialist
`March 2024 - April 2025`
Brigham Young University - Idaho

- Enhanced updating process efficiency from 13+ weeks to 1 day by developing 1 Google Script program with Canvas API application to pull out data and write it to tracker spreadsheet.
- Played a key role in team by setting and following up 1 personal learning goals each week to increase coding field knowledge
- Promoted open communication with team members and other departments by regularly attending social engagements

#### iOS Mobile Development
`March 2025 - September 2025`
The Church of Jesus Christ of Latter-day Saints

- Resolved over 100 UI and functional bugs to provide a better user experience for over 100,000 users
- Promoted open communication with team members to increase workflow smoothness by asking meaningful questions and sharing observations
- Reinvented over 50 accessibility features for VoiceOver users for Gospel Library App
- Built a recent image gallery feature for Gospel Library App to allow users to see new images each week



## Projects

#### SwiftUI Weather Mobile APP

`January 2025 - February 2025`
Student Personal Academic Project

- Founded and launched a mobile weather app for iOS devices to provide users with a nice look, clean, and easy-to-use weather app
- Implement OpenWeather API into application to update information according users' location and time
- [GitHub Repository](https://github.com/chengensung1219/iosweatherapp)

#### C++ Snake Game
`January 2025 - February 2025`
Student Personal Academic Project 

- Develop a snake game Implementing Raylib library to create a functional game with 2 systems (scoring system and trigger system)
- Applied 4 principles in object-oriented programming (abstraction, inheritance, polymorphism, and encapsulation) to design efficient and scalable solutions
- [GitHub Repository](https://github.com/chengensung1219/SnakeGame)

<!-- ### Footer

Last updated: Dec 2025 -->